apiVersion: v1
kind: Secret
metadata:
  name: {{ template "db.fullname" . }} 
  labels:
    app: {{ template "postgresql.name" . }}
type: Opaque
data:
  dbPassword: {{ .Values.postgres.Password | b64enc | quote  }}
