postgres:
  images: "registry.cn-hangzhou.aliyuncs.com/sxkj/postgres:11"
  imagePullPolicy: IfNotPresent
  secret: postgresecrets
  User: gogs
  Password: gogs
  usePasswordFile: false
  Database: gogs

  service:
    http:
      serviceType: NodePort
      port: 5432
      externalHost: gogs.lhf.com
    ssh:
      serviceType: ClusterIP
      port: 22

  resources:
    postgres:
      requests:
        memory: 200Mi
        cpu: 200m
      limits:
        memory: 2Gi
        cpu: 1

ingress:
  enabled: true
  hosts:
    - host: "gogs.lhf.com"
  ingress_annotations:
    kubernetes.io/ingress.class: nginx

persistence:
  enabled: ture
  gogsSize: 10Gi
  postgresSize: 5Gi
  storageClass: nas-storage
  accessMode: ReadWriteMany
  subPath: "postgresql-db"
  dataMountPath: /var/lib/postgresql/data/pgdata

